cd /c/_FLAP03/GBZZBEBJ/Working/dotnet/APieShop/Assets/Images

wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/caramelpopcorncheesecake.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/chocolatecheesecake.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/pistachecheesecake.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/fruitpies/pecanpie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/seasonal/birthdaypie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/blueberrycheesecake.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/cheesecake.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypie.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecake.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/caramelpopcorncheesecakesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/chocolatecheesecakesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/pistachecheesecakesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/fruitpies/pecanpiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/seasonal/birthdaypiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/applepiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/blueberrycheesecakesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/bethanyspieshop/cheesecakes/cheesecakesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/cherrypiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/christmasapplepiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/cranberrypiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/peachpiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/pumpkinpiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/rhubarbpiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrypiesmall.jpg"
wget "https://gillcleerenpluralsight.blob.core.windows.net/files/strawberrycheesecakesmall.jpg"

cp * ../../AlfsPieShop/Images/


